### ISSUE TITLE
Feature to print resolved version without invoking bazel

### ISSUE THREAD

**Issue by sitaktif** [bazelbuild/bazelisk#335] opened 2022-07-13 18:04 UTC
It would be great to get the resolved version of bazel without invoking bazel.

Running `bazelisk --version` takes ~0.5s, which is noticeable by users.

My use case involves caching items that solely depend on the version of bazel, and I would like to avoid invoking `bazel` altogether whenever it can be avoided.

**Comment by fweikert** [comment] 2024-02-06 16:05
Closing this as duplicate of https://github.com/bazelbuild/bazelisk/issues/440

**Closed by fweikert** 2024-02-06 16:05 UTC
